services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_PORT: "${DATABASE_PORT}"
      PORT: "${PORT}"
      jwt_secret: "${JWT_SECRET}"
    links:
      - "database:${HOST}"

  database:
    image: postgres:15-alpine
    # ports:
    #   - "${DATABASE_PORT}:${DATABASE_PORT}"
    # expose:
    #   - "${DATABASE_PORT}"
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - review-strategies-db:/var/lib/postgresql/data


volumes:
  review-strategies-db:
